### DISCUSSION TITLE
[Python] Script to change TranslucentTB options

### DISCUSSION THREAD

**Discussion by Spiritreader** [AutoDarkMode/Windows-Auto-Night-Mode#594] [Custom scripts]
### What is this?

With this custom script you can change any setting in the TranslucentTB settings json file.

### What are the requirements?

- Python 3.8.0 or later
- `py` or `python` in your path variables

### How do I configure this?
You can find the location of the config file here to check the available variables:
`%localappdata%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json`

You can then modify the config by accessing its dictionary like this:
```
  config["desktop_appearance"]["color"] = "#FFFFFF00"
  config["maximized_window_appearance"]["enabled"] = False
  config["start_opened_appearance"]["accent"] = "acrylic"
  ...
```

### Script

```python
import json,re
import sys
import codecs
import os


def on_light(config):
    # change what you need to change here for the light theme
    config["desktop_appearance"]["color"] = "#FFFFFF00"


def on_dark(config):
    # change what you need to change here for the dark theme
    config["desktop_appearance"]["color"] = "#00000000"


is_light = True if len(sys.argv) > 1 and sys.argv[1] == "light" else False
local_appdata = os.getenv("LOCALAPPDATA")

if len(sys.argv) > 1:
    print('mode:', sys.argv[1])
else:
    print('mode: dark (default)')

try:
    # you might need to change this path
    with codecs.open(f'{local_appdata}\\Packages\\28017CharlesMilette.TranslucentTB_v826wp6bftszj\\RoamingState\\settings.json', 'r+', 'utf-8-sig') as f:
            data = f.read()
            data = re.sub("^//.*","",data,flags=re.MULTILINE)

            config = json.loads(data, strict=False)
            if is_light:
                on_light(config)
            else:
                on_dark(config)
            f.truncate(0)
            f.seek(0)
            dump = json.dumps(config, indent=4)
            f.write('// See https://TranslucentTB.github.io/config for more information\n')
            f.write(dump)
except Exception as e:
    print(e)
    exit(-1)
```

Save as `change_translucenttb.py` or whatever you prefer.

#### How to debug
The script writes its state and any exceptions to stdout, which is picked up by Auto Dark Mode in the `service.log` file

### How should I set this up in the ADM scripts file?
Example ADM scripts configuration:

```yaml
Enabled: true
Component:
  Scripts:
  - Name: TranslucentTB
    # you might need to change the command to python depending on your path variables
    Command: py
    ArgsLight: [{YOUR_PATH_TO_THE_SCRIPT}\change_translucenttb.py, light]
    ArgsDark: [{YOUR_PATH_TO_THE_SCRIPT]\change_translucenttb.py, dark]
    AllowedSources: [Any]
    TimeoutMillis: 10000
```

Change the `{YOUR_PATH_TO_THE_SCRIPT}` placeholder to the location where your script resides at.

That's it.

You can find more info on how to configure ADM scripts here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

### Disclaimer

```
This script comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute and modify it however you like.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```
