### DISCUSSION TITLE
[Batch] Restart explorer script

### DISCUSSION THREAD

**Discussion by Spiritreader** [AutoDarkMode/Windows-Auto-Night-Mode#597] [Custom scripts]
### Info 

Please check out the responses below for more fine grained control of the explorer restart procecure. 

### What is this?

With this custom script you can automatically restart explorer when the theme switches.
This is intrusive and I don't recommend doing this, but here's the script nonetheless.
ALL of your explorer windows will close and will **not** re-open automatically.
Active copy processes may **abort**.

### Script

```batch
taskkill /f /IM explorer.exe

start explorer.exe

exit
```

Save as `restart_explorer.bat` or whatever you prefer.

### How should I set this up in the ADM scripts file?
Example ADM scripts configuration:

```yaml
Enabled: true
Component:
  Scripts:
  - Name: RestartExplorer
    Command: {YOUR_PATH_TO_THE_SCRIPT}\restart_explorer.bat
    AllowedSources: [Any]
```

Change the `{YOUR_PATH_TO_THE_SCRIPT}` placeholder to the location where your script resides at.

That's it.

You can find more info on how to configure ADM scripts here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

### Disclaimer

```
This script comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute and modify it however you like.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```

**Comment by faeinthebay** [comment]
I made a better version of the script that shows a dialog asking to restart Explorer.  It's a one-liner, so no script file is needed.  But you need Powershell and VBScript (they're enabled by default in Windows 8+).  Just paste the snippet into `scripts.yaml`, set `WorkingDirectory` to a valid directory, and make sure you enable scripts at the top of the file.  

```
  - Name: Prompt to restart Explorer on theme switch
    Command: powershell
    ArgsLight: [-command, "get-process | where-object {$_.MainWindowTitle -eq 'Restart Explorer after theme switch?'} | stop-process; If ($(New-Object -ComObject 'Wscript.Shell').Popup('Toggled to light mode. Close all Explorer processes and relaunch?',0,'Restart Explorer after theme switch?',4+32) -eq 6) {stop-process -name explorer –force; } Else {exit 0}"]
    ArgsDark: [-command, "get-process | where-object {$_.MainWindowTitle -eq 'Restart Explorer after theme switch?'} | stop-process; If ($(New-Object -ComObject 'Wscript.Shell').Popup('Toggled to dark mode. Close all Explorer processes and relaunch?',0,'Restart Explorer after theme switch?',4+32) -eq 6) {stop-process -name explorer –force; } Else {exit 0}"]
    AllowedSources: [TimeSwitchModule, NightLightTrackerModule, BatteryStatusChanged, SystemResume, Manual, ExternalThemeSwitch, SystemUnlock, Api]
```

Explanation: 
- `powershell -command` will start a PowerShell process and run the quoted commands
- `get-process ... stop-process;` will kill any windows with the same title.  I made the dialog title pretty unique, so it's unlikely to kill anything else.  This is useful for unattended computers that might go through multiple theme switches before somebody sees the dialog.  
- `$(New-Object -ComObject 'Wscript.Shell')` makes a VBScript/WScript shell, as an object
- `Popup()` is [a method in VBScript to show a dialog box](https://ss64.com/vb/popup.html).  
- `4+32` is Microsoft's janky way of instructing `Popup()` to make a windows with Yes/No buttons and a question mark icon.
- `-eq 6` checks if the Yes button was pressed.  If it was, the if-statement runs `stop-process` to kill explorer (which is automatically restarted).
- `AllowedSources` triggers the script from every event but system startup (since Explorer would already restart itself in that case).

_I have edited this comment a few times to improve comments and remove WorkingDirectory (it doesn't work on some installations)._

**Comment by boredwz** [comment]
## **Restart `explorer.exe` and restore tabs (PowerShell)**

> `🔔`&nbsp; _UPD: I created `adm_helper` script, it already contains “restart explorer” script, and also has additional features for more convenient use of ADM Scripts. Check it out: [`GitHub link`](https://github.com/boredwz/win_scripts?tab=readme-ov-file#auto-dark-mode-helper-script)_

> `🔔`&nbsp; _I don't know if it is possible to open a single window with multiple tabs on Windows 11._

More information about Restart Explorer script: [Gist](https://gist.github.com/boredwz/1511cb7f81f0c01f3373a3d2ad8a7e9d?permalink_comment_id=5188600#gistcomment-5188600)

## Code

### Restart explorer and restore tabs

``` powershell
$e='explorer';$t=@();(New-Object -co Shell.Application).Windows()|%{$t+=@{p=$_.LocationURL;w=if($_.Top -lt 0){if($_.Top -lt -8000){'min'}else{'max'}}else{'nor'}}};kill -n $e -for;sleep 1;if(!($null=ps $e -ea 0)){saps $e};sleep 4;$t|%{saps $_.p -win $_.w}
```

<br>

### Restart explorer and restore tabs (minimize all)

``` powershell
$e='explorer';$t=@();(New-Object -co Shell.Application).Windows()|%{$t+=$_.LocationURL};kill -n $e -for;sleep 1;if(!($null=ps $e -ea 0)){saps $e};sleep 4;$t|%{saps $_ -win min}
```

<br>



## **Usage with ADM `scripts.yaml`**

> `⚠️`&nbsp; _Be careful escaping quote symbols `"'\`, with nested powershell `"` too_

<br>

### Ready-to-Go solution: RestartExplorer without any external script

```yaml
Enabled: true
Component:
  Scripts:
  # Ready-to-Go solution: RestartExplorer without any external script
  - Name: == Restart explorer.exe ==
    Command: powershell
    ArgsLight: [-noni, -nol, -nop, -ep, bypass, -c, "$e='explorer';$t=@();(New-Object -co Shell.Application).Windows()|%{$t+=@{p=$_.LocationURL;w=if($_.Top -lt 0){if($_.Top -lt -8000){'min'}else{'max'}}else{'nor'}}};kill -n $e -for;sleep 1;if(!($null=ps $e -ea 0)){saps $e};sleep 4;$t|%{saps $_.p -win $_.w}"]
    ArgsDark: [-noni, -nol, -nop, -ep, bypass, -c, "$e='explorer';$t=@();(New-Object -co Shell.Application).Windows()|%{$t+=@{p=$_.LocationURL;w=if($_.Top -lt 0){if($_.Top -lt -8000){'min'}else{'max'}}else{'nor'}}};kill -n $e -for;sleep 1;if(!($null=ps $e -ea 0)){saps $e};sleep 4;$t|%{saps $_.p -win $_.w}"]
    AllowedSources: [Any]
```

<br>

### Some more examples

```yaml
Enabled: true
Component:
  Scripts:
  # RestartExplorer.ps1 + run a custom script
  - Name: restart explorer.exe + a script
    Command: powershell
    WorkingDirectory: C:\Users\USER\Desktop
    ArgsLight: [-nop, -ep, bypass, -c, ". \".\\RestartExplorer.ps1\";RestartExplorer;","& \".\\some_script.ps1\" Light"]
    ArgsDark:
    - -nop
    - -ep
    - bypass
    - -c
    - ". \".\\RestartExplorer.ps1\";RestartExplorer;"
    - "& \".\\some_script.ps1\""
    AllowedSources: [Any]

  # Run a custom PS script
  - Name: My script
    Command: powershell
    ArgsLight: [-nop, -ep, bypass, -f, "C:\\Users\\USER\\Desktop\\My script.ps1", Light]
    ArgsDark: [-nop, -ep, bypass, -f, "C:\\Users\\USER\\Desktop\\My script.ps1", Dark]
    AllowedSources: [Any]
```
