### DISCUSSION TITLE
[Shell] Auto Dark Mode for WSL2

### DISCUSSION THREAD

**Discussion by sayandipdutta** [AutoDarkMode/Windows-Auto-Night-Mode#652] [Custom scripts]
# What is this?
Change program (TUIs and GUIs) themes on WSL2 based on Windows theme switch by AutoDarkMode. Configured for `tmux`, `neovim`, `lazygit`, .etc. And you can easily add more.

# Script
You can find the script and more details in https://github.com/sayandipdutta/autodarkmode-wsl .

# How should I set this up in the ADM scripts file?
Example ADM scripts configuration:
```yaml
Enabled: true
Component:
  Scripts:
  # Other scripts (if any)
  - Name: autodarkmode_wsl
    Command: powershell
    ArgsLight: [-NoProfile, -Command, wsl path/to/repo/adm.sh 1]
    ArgsDark: [-NoProfile, -Command, wsl path/to/repo/adm.sh 0]
    AllowedSources: [Any]
```
Change the `path/to/repo/` placeholder to the location where your script resides at.

That's it.

You can find more info on how to configure ADM scripts here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

# Disclaimer
```
This script comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute and modify it however you like.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```

**Comment by Spiritreader** [comment]
Thank you!

I've added a script tag so people can find it easily.

**Comment by clsty** [comment]
**Tip:**

For some apps especially Gnome ones, install `glib2` (for Debian it's `libglib2.0-bin`) and then in `scripts.yaml`:
```yaml
Enabled: true
Component:
  Scripts:
  - Name: wsl Debian gsettings
    Command: cmd
    ArgsLight: [/c, wsl -d Debian exec gsettings set org.gnome.desktop.interface color-scheme prefer-light]
    ArgsDark: [/c, wsl -d Debian exec gsettings set org.gnome.desktop.interface color-scheme prefer-dark]
    AllowedSources: [Any]
```
Remember to replace `Debian` to here to your distro.
