### DISCUSSION TITLE
[Shell] Auto change wallpaper in Wallpaper Engine

### DISCUSSION THREAD

**Discussion by e-altunel** [AutoDarkMode/Windows-Auto-Night-Mode#703] [Custom scripts]
```yaml
Enabled: true
Component:
  TimeoutMillis: 10000
  Scripts:
  - Name: WallPaperEngine
    Command: {Your Steam Path}\steamapps\common\wallpaper_engine\wallpaper32.exe
    ArgsLight: [-control, openWallpaper, -file, {Your Steam Path}\steamapps\workshop\content\431960\{Wallpaper ID}\scene.pkg]
    ArgsDark:  [-control, openWallpaper, -file, {Your Steam Path}\steamapps\workshop\content\431960\{Wallpaper ID}\scene.pkg]
    AllowedSources: [Any]
```
This is my first-time using GitHub. I am sorry for not adding detailed description.

### How you can find Wallpaper ID
![image](https://user-images.githubusercontent.com/101647178/230869599-30d57d71-60e7-4057-a766-7c6a2b0ee8a0.png)
If you click copy url you will get:
https://steamcommunity.com/sharedfiles/filedetails/?id={Wallpaper ID}

**Comment by Spiritreader** [comment]
Thank you for the contribution! 
I've added the script label so people can find it easily.

**Comment by sapphired18** [comment]
I have to change the scene.pkg to video file to work with video wallpaper,
 ex: `D:\Games\SteamLibrary\steamapps\workshop\content\431960\2971481084\Stelle eating trash - Honkai star rail animation (1080p_25fps_H264-128kbit_AAC).mp4`
 
so the script is like this
 ```
 Enabled: true
Component:
  Scripts:
  - Name: WallpaperEngine
    Command: D://Games//SteamLibrary//steamapps//common//wallpaper_engine//wallpaper32.exe
    ArgsLight: [-control, openWallpaper, -file, '{Your Steam Path}\steamapps\workshop\content\431960\{Wallpaper ID}\{Video file}']
    ArgsDark: [-control, openWallpaper, -file, '{Your Steam Path}\steamapps\workshop\content\431960\{Wallpaper ID}\{Video file}']
    AllowedSources: [Any]
 ```

**Comment by KilluaAoki** [comment]
Some suggestions for wallpaper engine users, if you want to switch between different wallpapers in light mode or dark mode, you can set the active time period of each wallpaper in the wallpaper engine playlist, and at the same time in adm  Adjust the switching mode time to one minute before the corresponding time period of wallpaper engine.(forgive me for using translation software)

**Comment by andrii-malakhovtsev** [comment]
You can also do the same, but with playlists:

```script
Enabled: true
Component:
 Scripts:
 - Name: WallpaperEngine
   Command: {Your Steam Path}\steamapps\common\wallpaper_engine\wallpaper64.exe
   ArgsLight: [-control, openPlaylist, -playlist, "{light theme playlist}"]
   ArgsDark: [-control, openPlaylist, -playlist, "{dark theme playlist"]
   AllowedSources: [Any]
```

**Comment by ehehela** [comment]
I think following is better with playlists:
```yml
Enabled: true
Component:
  Scripts:
    # Wait a few seconds after system startup to prevent Wallpaper Engine from crashing
    - Name: WallPaperEngineWait30s
      Command: timeout
      ArgsLight: [/t, 15]
      ArgsDark: [/t, 15]
      AllowedSources: [Any]
      TimeoutMillis: 20000
    - Name: WallPaperEngineStop
      Command: C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper32.exe
      ArgsLight: [-control, stop]
      ArgsDark: [-control, stop]
      AllowedSources: [Any]
    - Name: WallPaperEngineSwitch
      Command: C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper32.exe
      ArgsLight: [-control, openPlaylist, -playlist, light]
      ArgsDark: [-control, openPlaylist, -playlist, dark]
      AllowedSources: [Any]
    - Name: WallPaperEnginePlay
      Command: C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper32.exe
      ArgsLight: [-control, play]
      ArgsDark: [-control, play]
      AllowedSources: [Any]
```
