### DISCUSSION TITLE
Run scripts after theme fully changed

### DISCUSSION THREAD

**Discussion by avi12** [AutoDarkMode/Windows-Auto-Night-Mode#749] [General]
**Describe the enhancement or feature you'd like**
Run the script after the theme has fully been changed

**Describe alternatives you've considered**
Toggling the theme manually, waiting until the pixels turn to the other side, and then doing the other task

**Additional context**
I wish to automate changing the theme to light and then putting the computer to sleep. This is to avoid the theme change as the computer wakes up, which lags it
I discovered [custom scripts](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts) yesterday, but the script executes as soon as I toggle the theme to light, which doesn't prevent the lag

**Comment by Spiritreader** [comment]
> Toggling the theme manually, waiting until the pixels turn to the other side, and then doing the other task

That is not possible because we don't have any telemtry over the theme switch.
We instruct Windows to set the theme and after that it's out of ADM's hands.
IThemeManager2 returns after it successfully received a switch call, *not* after the theme switch is fully complete.

If you want an execution delay you need to program it into your script.

**Comment by Armin2208** [comment]
You could put an sleep timer to your custom script

**Reply by avi12** [reply]
Indeed
Funny thing, I can't figure out how to properly restart ADM's service

**Reply by Armin2208** [reply]
AutoDarkModeShell.exe has a --restart argument

**Comment by avi12** [comment]
The following `scripts.yaml` gets the job done:
```yaml
# https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts
Enabled: true
Component:
  Scripts:
    - Name: Sleep
      Command: cmd
      ArgsLight:
        - /C
        - 'timeout 10 && rundll32 powrprof.dll,SetSuspendState 0,1,0'
```
However, you need to make sure to run the following [command](https://superuser.com/questions/42124/how-can-i-put-the-computer-to-sleep-from-command-prompt-run-menu) in an admin CMD window:
```cmd
powercfg -hibernate off
```
As [Armin2208](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/discussions/749#discussioncomment-6517798) mentioned, run the following to register the script:
```cmd
%LocalAppData%\Programs\AutoDarkMode\AutoDarkModeShell --restart
```

**Reply by avi12** [reply]
I updated the script to use PowerShell
```yaml
# https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts
Enabled: true
Component:
  Scripts:
    - Name: Sleep
      Command: pwsh
      TimeoutMillis: 11000
      AllowedSources: [Manual]
      ArgsLight:
        - -Command
        - '$date = Get-Date; if ($date.Hour -le 4 -or $date.Hour -ge 22) { Start-Sleep 10; rundll32 powrprof.dll,SetSuspendState 0,1,0 }'
```
