### DISCUSSION TITLE
Adobe Bridge Theme

### DISCUSSION THREAD

**Discussion by xmha97** [AutoDarkMode/Windows-Auto-Night-Mode#790] [Custom scripts]
```yaml
  - Name: Adobe Bridge
    Command: C:\Windows\System32\reg.exe
    WorkingDirectory: C:\Users\Muhammadhussein\AppData\Roaming\AutoDarkMode
    ArgsLight: [add "HKCU\Software\Adobe\Bridge 2024\Preferences" /v "ThemeBrightness" /t REG_BINARY /d "02000000" /f]
    ArgsDark: [add "HKCU\Software\Adobe\Bridge 2024\Preferences" /v "ThemeBrightness" /t REG_BINARY /d "01000000" /f]
    AllowedSources: [Any]
```
Why is this script not working?
