### DISCUSSION TITLE
[Batch]Day/Night theme switch for Sumatra PDF

### DISCUSSION THREAD

**Discussion by custard-pi** [AutoDarkMode/Windows-Auto-Night-Mode#799] [Custom scripts]
Auto Day/Night theme switch for [Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader) ([Github](https://github.com/sumatrapdfreader/sumatrapdf))  

Sumatra PDF uses a text file(%LOCALAPPDATA%\SumatraPDF\SumatraPDF-settings.txt) to store all its settings.  
In the settings file, "Theme = "string defines the theme used by the program, currently three themes are available:  
`"Theme = Light"`  
`"Theme = Dark"`  
`"Theme = Darker"`  

This script use [FART](https://github.com/lionello/fart-it) (Find And Replace Text command line utility) to replace theme settings in the settings file, switching the theme.

1.Save the following batch script as a .bat file (e.g. `C:\\Mydir\ThemeSwitch.bat`). 
```winbatch
REM Assuming your local app data directory is under C: drive
C:
cd  %LOCALAPPDATA%\SumatraPDF
IF "%1"=="-L" GOTO light
IF "%1"=="-D" GOTO dark
GOTO end

:light
"%~dp0\fart.exe" -w -q SumatraPDF-settings.txt "Theme = Darker" "Theme = Light"
GOTO end
:dark
"%~dp0\fart.exe" -w -q SumatraPDF-settings.txt "Theme = Light" "Theme = Darker"
:end
```
You can use "Theme = Dark" instead of "Theme = Darker" if you prefer the Dark theme as the night theme.    
2. Download the [latest release](https://github.com/lionello/fart-it/releases/latest) of FART, save the fart.exe in the same directory as the bat file(e.g. `C:\\Mydir\fart.exe`). 
3. Paste the following content into `scripts.yaml`
```yaml
Enabled: true
Component:
  Scripts:
  - Name: SumatraPDF
    Command: "{Path of the .bat}"
    ArgsLight: [-L]
    ArgsDark: [-D]
    AllowedSources: [Any]
```
replace`{Path of the .bat}` to the path of the bat file(e.g. `C:\\Mydir\ThemeSwitch.bat`).

**Comment by custard-pi** [comment]
rewrote with pwsh, no longer requires FART. 
1. `ThemeSwitch.ps1`
```pwsh
#SumatraPDF Day/Night Mode Switcher
# Check the argument passed in
$argument = $args[0]

# Read the content of the config file
$configFile = "$env:LOCALAPPDATA\SumatraPDF\SumatraPDF-settings.txt"
$configContent = Get-Content $configFile

$preferedLightTheme = "Light" # Change this to your prefered light theme
$preferedDarkTheme = "Darker" # Change this to your prefered dark theme

# Perform different tasks based on the argument
switch ($argument) {
    "-L" {
        # Switch to dark theme
        # Find and replace the configuration
        $newConfigContent = $configContent -replace "^Theme = $preferedDarkTheme$", "Theme = $preferedLightTheme"
        # Write the updated content back to the config file
        $newConfigContent | Set-Content $configFile
    }
    "-D" {
        # Switch to light theme
        # Find and replace the configuration
        $newConfigContent = $configContent -replace "^Theme = $preferedLightTheme$", "Theme = $preferedDarkTheme"
        # Write the updated content back to the config file
        $newConfigContent | Set-Content $configFile
    }
    default {
        Write-Host "Invalid argument."
    }
}
````
2.scripts.yaml
```yaml
Enabled: true
Component:
  Scripts:
  - Name: SumatraPDF
    Command: pwsh
    WorkingDirectory: "{directory where ThemeSwitch.ps1 is stored in}"
    ArgsLight: [./ThemeSwitch.ps1, -L]
    ArgsDark: [./ThemeSwitch.ps1, -D]
    AllowedSources: [Any]
```

**Comment by neptotech** [comment]
Rewrote it such that it actually gives black background, white text dark mode for better eyes:

scripts.yaml
```
Enabled: true
Component:
  Scripts:
  - Name: theme
    Command: C:\Scripts\sumatra\script.bat
    ArgsLight: [light]
    ArgsDark: [dark]
    AllowedSources: [Any]
```
--------------------
C:\Scripts\sumatra\script.bat
```
@echo off
python "%~dp0sw.py" %*
```

-------------------
C:\Scripts\sumatra\sw.py
```
import sys
import os
import re

darktype = 1 #1, 2  
lighttype = 3 #1,2,3

CONFIG_PATH = os.path.expanduser(r"~\AppData\Local\SumatraPDF\SumatraPDF-settings.txt")

if len(sys.argv) < 2:
    print("Usage: python theme_switcher.py [light|dark]")
    sys.exit(1)

mode = sys.argv[1].lower()

if mode == "light":
    if lighttype==1:
        text_color = "#000000"
        background_color = "#f9f5ea"
    elif lighttype==2:
        text_color = "#000000"
        background_color = "#000000"
    else:
        text_color = "#000000"
        background_color = "#fdf6e3"
    theme = "Solarized Light"
elif mode == "dark":
    if darktype==1:
        text_color = "#d9d9d9"
        background_color = "#212121"
    else:
        text_color = "#b2b2b2"
        background_color = "#242424"
    theme = "Dark"
else:
    print("Invalid argument. Use 'light' or 'dark'.")
    sys.exit(1)

# Read settings
with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    content = f.read()

# Replace FixedPageUI colors
content = re.sub(r"(TextColor\s*=\s*)#[0-9A-Fa-f]{6}", rf"\1{text_color}", content)
content = re.sub(r"(BackgroundColor\s*=\s*)#[0-9A-Fa-f]{6}", rf"\1{background_color}", content)

# Replace Theme
content = re.sub(r"(Theme\s*=\s*).+", rf"\1{theme}", content)

# Save changes
with open(CONFIG_PATH, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Applied {mode} theme successfully!")
```

Dark type has two modes edge reader theme,and chatgpt dark theme pdf. light type has few too
You can run it if required via `python sw.py light` or `dark` as well.

P.S: yeah too many files to copy paste, I didn't have time to simplify the process did for self-purpose to save my eyes.
<img width="1220" height="409" alt="image" src="https://github.com/user-attachments/assets/07af862a-765a-493d-a063-a448530555f6" />
<img width="1225" height="402" alt="image" src="https://github.com/user-attachments/assets/35762cdd-0ca5-47c2-8d46-5cb46aa2852c" />
