### DISCUSSION TITLE
change brightness with powershell script without third-part software

### DISCUSSION THREAD

**Discussion by ExcuseLme** [AutoDarkMode/Windows-Auto-Night-Mode#835] [Custom scripts]
## create a powershell script like "changeBrightness.ps1"

content:(generated by chatGPT) 
```powershell
param(
    [int]$b # lightLevel（range：0-100）
)

# check if the lightLevel is valid
if ($b -lt 0 -or $b -gt 100) {
    Write-Host "Error: Brightness level must be between 0 and 100."
    exit
}

# change screen's brightness with WMI
$namespace = "root\WMI"
$query = "SELECT * FROM WmiMonitorBrightnessMethods"
$monitor = Get-WmiObject -Namespace $namespace -Query $query
$monitor.WmiSetBrightness(1, $b)
```

## edit AutoDarkMode's script
```yml
Enabled: true
Component:
  TimeoutMillis: 3000
  Scripts:
  - Name: ChangeBrightnessScript
    Command: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    ArgsLight: [${pathToYourScriptsDir\changeBrightness.ps1}, -b, 95]
    ArgsDark: [${pathToYourScriptsDir\changeBrightness.ps1}, -b, 80]
    AllowedSources: [Any]
```

## all done
