### DISCUSSION TITLE
I'm Confused about scope

### DISCUSSION THREAD

**Discussion by Jbuck7** [AutoDarkMode/Windows-Auto-Night-Mode#884] [Q&A]
Hello! I just spent hours to get a script working. All it does is run some spicetify commands using .bat files thru cmd. The issue ended up being that AutoDarkMode didn't know what or where spicetify was. I fixed it by including the entire path in the bat files instead of just "spicetify". The part I am having trouble with is why when I ran the .bat files by clicking or thru win+r they ran fine but ADM couldn't? Does ADM run at like a higher scope than win+R?

**Comment by Spiritreader** [comment]
You most likely want to run spicetify through something like this
```
  - Name: MyOtherApp
    # Example for calling cmd silently
    # You can replace the "echo I am a dark command" with a patch to a batch file
    # This will call the batch file without displaying a console window
    Command: cmd
    ArgsLight: 
      - /c
      - echo I am a light command
    ArgsDark: [/c, echo I am a dark command]
```

ADM does not know what spicetify is because the script runner is not a shell environment. If you want to run spicetify directly you'd need to provide the absolute path to it, or, as in the example above, run it with the command above, where you replace the "echo I am a X command" line with whatevery spicetify command you need.
