### DISCUSSION TITLE
Auto change wallpaper in Lively Wallpaper

### DISCUSSION THREAD

**Discussion by Shegooo** [AutoDarkMode/Windows-Auto-Night-Mode#907] [Custom scripts]
1. **Dowload livelycu.exe from Command Line Controls of Lively on github**

2. **Get Your Wallpaper Paths**
- Open Lively Wallpaper, right-click on the wallpaper you want to select -> Open File Location.
- Copy the path (e.g., path/to/light.abc).
- Repeat this step to get the path for your Dark Mode wallpaper.

3. **Create the Batch Files**

_**For Light Mode (save as livelylight.bat):**_

`@echo off
timeout /t 2 /nobreak >nul
cd /d "path/to/folder/have/livelycu.exe"
livelycu.exe setwp --file "path/to/light.abc"`

_**For Dark Mode (save as livelydark.bat):**_

`@echo off
timeout /t 2 /nobreak >nul
cd /d "path/to/folder/have/livelycu.exe"
livelycu.exe setwp --file "path/to/dark.abc"`

5. **Configure Auto Dark Mode**
**_Apply the following settings to your Auto Dark Mode configuration file:_**

```
Enabled: true
Component:
  Scripts:
  - Name: Lively Wallpaper Switcher
    Command: cmd
    WorkingDirectory: %YOUR_SCRIPT_FOLDER-PATH%
    ArgsLight: [/c, livelylight.bat]
    ArgsDark: [/c, livelydark.bat]
    AllowedSources: [Any]
    TimeoutMillis: 10000
```
