### ISSUE TITLE
Running powershell script with admin rights

### ISSUE THREAD

**Issue by JulienMaille** [AutoDarkMode/Windows-Auto-Night-Mode#745]
I'm trying to change the brightness of my NUC leds at night and the only way I was able to do that is through [WMI](https://learn.microsoft.com/fr-fr/windows/win32/wmisdk/wmi-start-page)
I can call that from a powerwhell script, but it only works with admin permissions. Is there anything I can do?

```
2023-07-15 16:32:56 | Warn | ScriptHandler.Launch: Powershell Example's output does not indicate success: Get-WmiObject : Access denied‚ 
At character D:\Codez\NucLeds\AutoDark.ps1:31 : 9
+ $cisd = Get-WmiObject -Namespace "ROOT\WMI" -Class CISD_WMI
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

```powershell
[int]$brightness = 64
if ( $Args[0] -eq "0" ) {
    $brightness = 5
}

$cisd = Get-WmiObject -Namespace "ROOT\WMI" -Class CISD_WMI

$bytes = [byte]0, 0, 0, $brightness;
$cisd.SetValueIndicatorOptionLedType([bitconverter]::ToInt32($bytes, 0)).Data.Bytes[0,1,2,3]
$bytes = [byte]2, 0, 0, $brightness;
$cisd.SetValueIndicatorOptionLedType([bitconverter]::ToInt32($bytes, 0)).Data.Bytes[0,1,2,3]

$cisd.AppNotify(0x1).Data
```

**Comment by Spiritreader** [comment]
Sadly not at the moment.
Auto Dark Mode cannot run as elevated or elevate commands at the moment.
Micrsoft Powertoys has an option to make the application run as administrator on demand.
We may be able to look into this at some point, but it's not on the short term list of features.

__________________

> Is there anything I can do?

I may be able to offer a workaround though. I haven't tested this but I think this could potentially work:

What you can do is create a task in Windows Task Scheduler beforehand using its UI and configure your powershell script to run as elevated there. 
https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts/

Then it should be possible to call that task in ADM without administrator rights within powershell: https://learn.microsoft.com/en-us/powershell/module/scheduledtasks/start-scheduledtask?view=windowsserver2019-ps

The flow would be something like this
```
Task (elevated, run as admin) <-calls- Windows Task Scheduler <-calls- Script <-calls- Auto Dark Mode
```

**Comment by JulienMaille** [comment]
@Spiritreader Thanks for your suggested workaround. I have successfully created the scheduled tasks.
I'm now trying to run them from ADM with a powershell "one line". I did not want to create a script that start the task that starts the other script.
I tried `powershell -Command "Start-ScheduledTask -TaskName NucLedNight"` from the console and it works.
but from ADM config
```yaml
  Scripts:
  - Name: Powershell Example
    Command: powershell
    ArgsLight: [ -Command "Start-ScheduledTask -TaskName NucLedDay" ]
    ArgsDark: [ -Command "Start-ScheduledTask -TaskName NucLedNight" ]
```
It seems you had extra quotes around the argument and it fails:
```log
2023-07-18 21:10:05 | Info | ScriptHandler.Launch: running Powershell Example: "powershell" "-Command "Start-ScheduledTask -TaskName NucLedDay"" 
```

**Comment by JulienMaille** [comment]
ok, it seems I got it working with following syntax:
```yaml
Enabled: true
Component:
  Scripts:
  - Name: Powershell Example
    Command: powershell
    ArgsLight:
     - -Command
     - "Start-ScheduledTask -TaskName NucLedDay"
    ArgsDark:
     - -Command
     - "Start-ScheduledTask -TaskName NucLedNight"
    AllowedSources: [Any]
```
