### ISSUE TITLE
Environment variables in Script working directory

### ISSUE THREAD

**Issue by atahrijouti** [AutoDarkMode/Windows-Auto-Night-Mode#751]
On a script I am working on to dynamically change the color scheme of helix-editor, I am trying to only use a relative path to the current user's home `%AppData%` directory like so

```yaml
Enabled: true
Component:
  Scripts:
  - Name: Toggle helix theme
    Command: sh
    WorkingDirectory: %AppData%\Roaming\helix
    ArgsLight: [-c, sed -i -E 's/(theme\s=\s").*(")/\1my_light-theme\2/' config.toml]
    ArgsDark: [-c, sed -i -E 's/(theme\s=\s").*(")/\1my_dark_theme\2/' config.toml]
    AllowedSources: [Any]
    TimeoutMillis: 
```

unfortunately I receive the following error in the log
```
script configuration could not be loaded. All scripts inactive: SyntaxErrorException > (Line: 6, Col: 23, Idx: 108) - (Line: 6, Col: 24, Idx: 109): While scanning for the next token, found character that cannot start any token. > Void FetchNextToken()
```

Is this the expected behaviour for the WorkingDirectory option? Is there any way to use Environment variables instead of the absolute path ?

Thank you

**Comment by Spiritreader** [comment]
The reason for getting this error message is that yaml doesn't allow raw % characters.
Thus you are attempting to load an invalid yaml file, which fails.

If you want to represent those characters, you need to single-quote your string like this
```yaml
Enabled: true
Component:
  Scripts:
  - Name: Toggle helix theme
    Command: sh
    WorkingDirectory: '%AppData%\Roaming\helix'
    ArgsLight: [-c, sed -i -E 's/(theme\s=\s").*(")/\1my_light-theme\2/' config.toml]
    ArgsDark: [-c, sed -i -E 's/(theme\s=\s").*(")/\1my_dark_theme\2/' config.toml]
    AllowedSources: [Any]
    TimeoutMillis: 
```
