### ISSUE TITLE
Accent Color on Start and Taskbar does not change

### ISSUE THREAD

**Issue by Lyhtande** [AutoDarkMode/Windows-Auto-Night-Mode#911]
### Description

I use ADM with the following settings:
**Time of day**

1. Automatic design change is activated (the error also occurs if this option is not activated)

**Personalization**

1. Windows manages the theme
2. Windows theme change is activated
3. A light and a dark theme is defined

**The issue**
ADM does not apply the accent color on start and taskbar as defined in the light and dark themes. The slider for “Show accent color on start and taskbar” is deactivated each time the design is changed.

### Expected Behavior

ADM should apply the accent color on start and taskbar as defined in the themes and should leave the slider for “Show accent color on start and taskbar” activated with every design change.

### Log Data

[service.log](https://github.com/user-attachments/files/18546371/service.log)

### Commit Hash, Version and Windows Build

Windows 11 Pro 23H2 22631.4751

**Comment by Lyhtande** [comment]
Perhaps this could be solved using a batch file, as described [here](https://www.tenforums.com/customization/134313-how-do-i-change-refresh-accentcolor-via-command-line.html)?
What exactly would I have to write in the batch file for Windows 11?

**Comment by Lyhtande** [comment]
Update:
I think I was able to solve it now with a yaml script:

```
Enabled: true
Component:
  Scripts:
    - Name: Set Accent Color for Taskbar and Start Menu
      Command: powershell.exe
      WorkingDirectory: "I:\\Documents\\_ Backups Software\\ADM"
      ArgsLight: ["-ExecutionPolicy", "Bypass", "-File", "I:\\Documents\\_ Backups Software\\ADM\\update-colorprevalence.ps1"]
      ArgsDark: ["-ExecutionPolicy", "Bypass", "-File", "I:\\Documents\\_ Backups Software\\ADM\\update-colorprevalence.ps1"]
      AllowedSources: [Any]
      TimeoutMillis: 3000
```
